=== Emaya009/Solvd-Intern-Project-Homework15/XMLparser/pharmacy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="pharmacy" type="pharmacyType"/>
  <xs:complexType name="customerType">
    <xs:sequence>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="John Doe"/>
            <xs:enumeration value="Jane Smith"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="address">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="123 Main St."/>
            <xs:enumeration value="456 Elm St."/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="city"/>
      <xs:element type="xs:string" name="state"/>
      <xs:element type="xs:string" name="zip"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="customersType">
    <xs:sequence>
      <xs:element type="customerType" name="customer" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="doctorType">
    <xs:sequence>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Dr. John Smith"/>
            <xs:enumeration value="Dr. Jane Doe"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="specialty">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Pediatrics"/>
            <xs:enumeration value="Cardiology"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="doctorsType">
    <xs:sequence>
      <xs:element type="doctorType" name="doctor" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="medicine_orderType">
    <xs:sequence>
      <xs:element name="customer_id">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="doctor_id">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="date">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2023-04-05"/>
            <xs:enumeration value="2023-04-06"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="medicine_ordersType">
    <xs:sequence>
      <xs:element type="medicine_orderType" name="medicine_order" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="prescription_itemType">
    <xs:sequence>
      <xs:element name="medicine_order_id">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="drug_name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Lipitor"/>
            <xs:enumeration value="Zoloft"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="dosage">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="20mg"/>
            <xs:enumeration value="50mg"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="prescription_itemsType">
    <xs:sequence>
      <xs:element type="prescription_itemType" name="prescription_item" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="pharmacyType">
    <xs:sequence>
      <xs:element type="customersType" name="customers"/>
      <xs:element type="doctorsType" name="doctors"/>
      <xs:element type="medicine_ordersType" name="medicine_orders"/>
      <xs:element type="prescription_itemsType" name="prescription_items"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Emaya009/Solvd-Intern-Project-Homework15/XMLparser/pharmacy.xml
<?xml version="1.0" encoding="UTF-8"?>
<pharmacy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="pharmacy.xsd">
    <customers>
        <customer id="1">
            <name>John Doe</name>
            <address>123 Main St.</address>
            <city>Anytown</city>
            <state>CA</state>
            <zip>12345</zip>
        </customer>
        <customer id="2">
            <name>Jane Smith</name>
            <address>456 Elm St.</address>
            <city>Anytown</city>
            <state>CA</state>
            <zip>12345</zip>
        </customer>
    </customers>
    <doctors>
        <doctor id="1">
            <name>Dr. John Smith</name>
            <specialty>Pediatrics</specialty>
        </doctor>
        <doctor id="2">
            <name>Dr. Jane Doe</name>
            <specialty>Cardiology</specialty>
        </doctor>
    </doctors>
    <medicine_orders>
        <medicine_order id="1">
            <customer_id>1</customer_id>
            <doctor_id>1</doctor_id>
            <date>2023-04-05</date>
        </medicine_order>
        <medicine_order id="2">
            <customer_id>2</customer_id>
            <doctor_id>2</doctor_id>
            <date>2023-04-06</date>
        </medicine_order>
    </medicine_orders>
    <prescription_items>
        <prescription_item id="1">
            <medicine_order_id>1</medicine_order_id>
            <drug_name>Lipitor</drug_name>
            <dosage>20mg</dosage>
        </prescription_item>
        <prescription_item id="2">
            <medicine_order_id>2</medicine_order_id>
            <drug_name>Zoloft</drug_name>
            <dosage>50mg</dosage>
        </prescription_item>
    </prescription_items>
</pharmacy>
